In [1]:
# convolutional neural network on MNIST dataset

In [64]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [65]:
data = pd.read_csv('mnist.csv')

In [67]:
data.head()

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]

In [68]:
#reshaping into 28x28 because its  black and white images
data.iloc[3,1:].values.reshape(28,28).astype('uint8')

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0, 220, 179,   6,   0,   0,   0,   0,
          0,   0,   0,   0,   9,  77,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [69]:
#processing data


In [70]:
#storing pixel array in form length 28, width 28, and channel 1 in df_x
df_x = data.iloc[:, 1:].values.reshape(len(data),28,28,1)

#storing the lebels in y
y= data.iloc[:,0].values

### convert labels into catogorical data 
### convert labels to catagorical and each colum represents it own values declared above i.e 10

In [14]:
import keras

In [15]:
df_y = keras.utils.to_categorical(y,num_classes = 10)

In [16]:
df_x = np.array(df_x)
df_y - np.array(df_y)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [18]:
df_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [19]:
df_x.shape

(42000, 28, 28, 1)

In [20]:
#test and train

x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.2, random_state=4)

## CNN

In [38]:
model = Sequential()
model.add(Convolution2D(32,3,data_format='channels_last', activation = 'relu', input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss= 'categorical_crossentropy', optimizer='adadelta',metrics=['accuracy'])

In [45]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_10 (Dense)             (None, 100)               540900    
_________________________________________________________________
dropout_5 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 10)                1010      
_________________________________________________________________
activation_1 (Activation)    (None, 10)               

In [46]:
#fittingit with 100 images for testing
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs = 10)

Train on 33600 samples, validate on 8400 samples
Epoch 1/10
33600/33600 [==============================] - 24s 701us/step - loss: 0.1418 - accuracy: 0.9587 - val_loss: 0.1100 - val_accuracy: 0.9687
Epoch 2/10
33600/33600 [==============================] - 25s 731us/step - loss: 0.0985 - accuracy: 0.9707 - val_loss: 0.1208 - val_accuracy: 0.9686
Epoch 3/10
33600/33600 [==============================] - 23s 697us/step - loss: 0.0831 - accuracy: 0.9752 - val_loss: 0.1043 - val_accuracy: 0.9733
Epoch 4/10
33600/33600 [==============================] - 25s 743us/step - loss: 0.0694 - accuracy: 0.9795 - val_loss: 0.0991 - val_accuracy: 0.9730
Epoch 5/10
33600/33600 [==============================] - 24s 710us/step - loss: 0.0597 - accuracy: 0.9829 - val_loss: 0.1010 - val_accuracy: 0.9751
Epoch 6/10
33600/33600 [==============================] - 24s 724us/step - loss: 0.0525 - accuracy: 0.9850 - val_loss: 0.1161 - val_accuracy: 0.9729
Epoch 7/10
33600/33600 [==============================] -

In [47]:
model.evaluate(x_test,y_test)

8400/8400 [==============================] - 2s 215us/step


[0.11970370240493919, 0.977142870426178]

In [49]:
model.predict(x_test)

array([[1.0000000e+00, 2.6402529e-15, 8.9194468e-12, ..., 4.2569727e-16,
        2.1457354e-09, 1.8899555e-14],
       [6.3163624e-15, 4.0941897e-15, 9.1775660e-16, ..., 7.4853237e-13,
        1.9818987e-15, 2.0100007e-08],
       [9.9999964e-01, 1.5918613e-16, 2.2342182e-12, ..., 3.4942983e-15,
        1.9658150e-11, 8.9242936e-12],
       ...,
       [9.9997234e-01, 1.4104292e-11, 1.6702277e-14, ..., 1.4303335e-18,
        4.5945049e-12, 4.8918107e-13],
       [3.2765224e-23, 1.3149778e-21, 3.6895259e-19, ..., 1.8249601e-16,
        1.7333220e-14, 5.2184959e-17],
       [1.1879275e-14, 9.9999905e-01, 1.4358375e-12, ..., 2.0746823e-11,
        2.0590611e-09, 1.4005608e-12]], dtype=float32)

In [55]:
import matplotlib.pyplot as plt


In [56]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)